# Metrics related
UNZIP_TIMEOUT: "10s"

TASKS_GALLERY:
  # PR
  - TASK: "PR_PUBLIC"
    METRIC: "PER"
    GROUND_TRUE: "./ground_true/PR_PUBLIC/"
  - TASK: "PR_TEST"
    METRIC: "PER"
    GROUND_TRUE: "./ground_true/PR_TEST/"
  # KS
  - TASK: "KS_PUBLIC"
    METRIC: "ACC"
    GROUND_TRUE: "./ground_true/KS_PUBLIC/"
  - TASK: "KS_TEST"
    METRIC: "ACC"
    GROUND_TRUE: "./ground_true/KS_TEST/"
  # IC
  - TASK: "IC_PUBLIC"
    METRIC: "ACC"
    GROUND_TRUE: "./ground_true/IC_PUBLIC/"
  - TASK: "IC_TEST"
    METRIC: "ACC"
    GROUND_TRUE: "./ground_true/IC_TEST/"
  # SID
  - TASK: "SID_PUBLIC"
    METRIC: "ACC"
    GROUND_TRUE: "./ground_true/SID_PUBLIC/"
  - TASK: "SID_TEST"
    METRIC: "ACC"
    GROUND_TRUE: "./ground_true/SID_TEST/"
  # ER
  - TASK: "ER_PUBLIC"
    METRIC: "ACC"
    GROUND_TRUE: "./ground_true/ER_PUBLIC/"
  - TASK: "ER_TEST"
    METRIC: "ACC"
    GROUND_TRUE: "./ground_true/ER_TEST/"
  # ASR w/ LM
  - TASK: "ASR_W_LM_PUBLIC"
    METRIC: "WER"
    GROUND_TRUE: "./ground_true/ASR_PUBLIC/"
  - TASK: "ASR_W_LM_TEST"
    METRIC: "WER"
    GROUND_TRUE: "./ground_true/ASR_TEST/"
  # ASR w/o LM
  - TASK: "ASR_WO_LM_PUBLIC"
    METRIC: "WER"
    GROUND_TRUE: "./ground_true/ASR_PUBLIC/"
  - TASK: "ASR_WO_LM_TEST"
    METRIC: "WER"
    GROUND_TRUE: "./ground_true/ASR_TEST/"
  # QbE
  - TASK: "QbE_PUBLIC"
    METRIC: "MTWV"
    GROUND_TRUE: "./ground_true/QbE_PUBLIC/"
  - TASK: "QbE_TEST"
    METRIC: "MTWV"
    GROUND_TRUE: "./ground_true/QbE_TEST/"
  # SF # F1
  - TASK: "SF_PUBLIC"
    METRIC: "F1"
    GROUND_TRUE: "./ground_true/SF_PUBLIC/"
  - TASK: "SF_TEST"
    METRIC: "F1"
    GROUND_TRUE: "./ground_true/SF_TEST/"
  # SF # CER
  - TASK: "SF_PUBLIC"
    METRIC: "CER"
    GROUND_TRUE: "./ground_true/SF_PUBLIC/"
  - TASK: "SF_TEST"
    METRIC: "CER"
    GROUND_TRUE: "./ground_true/SF_TEST/"
  # ASV
  - TASK: "ASV_PUBLIC"
    METRIC: "EER"
    GROUND_TRUE: "./ground_true/ASV_PUBLIC/"
  - TASK: "ASV_TEST"
    METRIC: "EER"
    GROUND_TRUE: "./ground_true/ASV_TEST/"
  # SD
  - TASK: "SD_PUBLIC"
    METRIC: "DER"
    GROUND_TRUE: "./ground_true/SD_PUBLIC/"
  - TASK: "SD_TEST"
    METRIC: "DER"
    GROUND_TRUE: "./ground_true/SD_TEST/"
